import random
from typing import Dict, Tuple, List
from collections import defaultdict

import numpy as np
import pandas as pd
from qiskit import QuantumCircuit

import structure
from structure import Circuit

n_gram_stats: Dict[Tuple[str], List[float]] = defaultdict(list)

class Node:
    def __init__(self, state: Circuit, max_depth: int, parent=None):
        """
        A node in the tree stores information to guide the search.

        :param state: Circuit object representing the quantum circuit stored in the node.
        :param parent: Parent node. None for the root node.
        :param max_depth: Maximum depth allowed for the quantum circuit.
        """
        # Quantum circuit
        self.state = state
        # Is the circuit respecting the constraint of the hardware? boolean
        self.isTerminal = False

        # (In case the node is a grouping node)
        self.group = None
        self.is_finite = True
        self.evaluation_value = None
        self.to_expand = []

        # Parent node. Node object. The root node is the only one not having that.
        self.parent = parent
        # List of children of the node. list
        self.children = []
        # Number of times the node have been visited. integer
        self.visits = 0
        # Value is the total reward. float
        self.value = 0
        # Sum of squared values (needed for UCB-tuned)
        self.squared_value = 0.0
        # accumulated RAVE value (needed for RAVE)
        self.q_rave = 0
        # Number of RAVE visits (needed for RAVE)
        self.n_rave = 0
        # Store past values (needed for n-grams)
        self.n_gram_values = []
        # Maximum quantum circuit depth
        self.max_depth = max_depth
        # Position of the node in terms of tree depth. integer
        self.tree_depth = 0 if parent is None else parent.tree_depth + 1
        # Gate set
        self.gate_set = "continuous"  # TODO: Check into this
        # Control on the stop action of the node
        self.stop_is_done = False
        # Specify the action that created it, None only for root and stop nodes

        # Counts the Controlled-NOT gates in the circuit
        self.counter_cx = self.state.circuit.count_ops().get("cx", 0)

    def __repr__(self):
        return f"Tree depth: {self.tree_depth}  -  Generated by: {self.group}  -  Number of Children: {len(self.children)}  -  Visits: {self.visits}  -  Value: {self.value}  -  Quantum Circuit (CNOT counts)= {self.counter_cx}):\n{self.state.circuit}"

    def is_fully_expanded(
        self, branches, pw_C, pw_alpha, finite_progressive_widening: bool
    ):
        """
        Checks if the node is fully expanded.

        :param branches: int or boolean. If false, it uses progressive widening (PW), if true it uses double (PW). If int, the maximum number of branches is fixed.
        :param pw_alpha: float (in [0,1]). Closer to 1 in strongly stochastic domains, closer to 0 otherwise.
        :param pw_C: int. Hyperparameter for progressive widening.
        :return: Boolean indicating if the node is fully expanded (leaf).
        """
        if not self.children:
            return False

        if not self.is_finite or self.to_expand:
            if isinstance(branches, bool):
                # Progressive Widening Techniques: adaptive number of branches
                if branches:
                    raise NotImplementedError(
                        "Double progressive widening is not implemented yet."
                    )
                t = self.visits
                k = np.ceil(pw_C * (t**pw_alpha))
                return len(self.children) >= k
            elif isinstance(branches, int):
                # The number of the tree's branches is fixed
                return len(self.children) >= branches
            else:
                raise TypeError("The 'branches' parameter must be an int or bool.")

        return True

    def best_child(self, criteria):
        children_with_values = [
            (child, child.value, child.visits) for child in self.children
        ]
        if isinstance(criteria, str):
            if criteria == "value":
                best = max(children_with_values, key=lambda x: x[1])[0]
            elif criteria == "average_value":
                best = max(children_with_values, key=lambda x: x[1] / x[2])[0]
            elif criteria == "visits":
                best = max(children_with_values, key=lambda x: x[2])[0]
            else:
                raise ValueError(
                    "this variable can only be: visits, value, average_value"
                )
        else:
            raise TypeError("the variable criteria must be a string")
        return best


def node_from_qc(
    quantum_circuit: QuantumCircuit, parent_node: Node, roll_out: bool
) -> Node:
    if isinstance(quantum_circuit, QuantumCircuit):
        new_state = Circuit(4, 1).building_state(quantum_circuit)
        new_child = Node(new_state, max_depth=parent_node.max_depth, parent=parent_node)
        if not roll_out:
            parent_node.children.append(new_child)
        return new_child
    else:
        raise TypeError(
            "The quantum_circuit must be a QuantumCircuit object in Qiskit."
        )


def select(
    node: Node, exploration: float = 0.4, max_terminal_visits: float = float("+inf"), method: str = 'UCB', n: int = 2
) -> Node:
    log_visits = np.log(node.visits)

    children_with_values = []
    for child in node.children:
        if child.isTerminal and child.visits > max_terminal_visits:
            continue

        match method:
            case 'UCB':
                value = _selection_ucb(child.value, child.visits, node.visits, exploration)
            case 'UCB-tuned':
                value = _selection_ucb_tuned(child.value, child.visits, node.visits, child.squared_value, exploration)
            case 'UCB-tuned-1.41':
                value = _selection_ucb_tuned(child.value, child.visits, node.visits, child.squared_value, 1.41)
            case 'UCB-tuned-0.4':
                value = _selection_ucb_tuned(child.value, child.visits, node.visits, child.squared_value, 0.4)
            case 'RAVE':
                q_uct = _selection_ucb(child.value, child.visits, node.visits, exploration)
                q_rave = child.q_rave / child.n_rave if child.n_rave > 0 else 0
                value = _selection_RAVE(q_rave, q_uct, child.n_rave)
            case 'RAVE-0.5':
                q_uct = _selection_ucb(child.value, child.visits, node.visits, exploration)
                q_rave = child.q_rave / child.n_rave if child.n_rave > 0 else 0
                value = _selection_RAVE(q_rave, q_uct, child.n_rave, 0.5)
            case 'n-grams':
                seq = _get_last_n_actions(child, n)
                values = n_gram_stats.get(tuple(seq), [])
                value = np.mean(values) if values else 0
        
        children_with_values.append(
            (
                child,
                value
            )
        )
    return max(children_with_values, key=lambda x: x[1])[0]

def _selection_ucb(w_i: float, n_i: int, N: int, C: float) -> float:
    if n_i == 0:
        return np.inf  # Infinite value for unvisited nodes
    return (w_i / n_i) + C * np.sqrt(np.log(N) / n_i)

def _selection_ucb_tuned(w_i: float, n_i: int, N: int, S_i: float, C: float = 1.0) -> float:
    """UCB1-Tuned selection formula considering variance."""
    if n_i == 0:
        return np.inf
    v_i = _compute_variance(w_i, S_i, n_i)
    exploration_factor = C * np.sqrt((np.log(N) / n_i) * min(0.25, v_i + np.sqrt(np.log(N) / n_i)))
    return (w_i / n_i) + exploration_factor


def _compute_variance(w_i: float, S_i: float, n_i: int) -> float:
    """Compute empirical variance for UCB-Tuned."""
    if n_i == 0:
        return 0.0
    mean_reward = w_i / n_i
    return (S_i / n_i) - (mean_reward ** 2)

def _selection_RAVE(q_rave: float, q_uct: float, n: int, b: float = 1.0) -> float:
    """RAVE selection formula combining UCB and heuristic action values."""
    beta = b / (b + n) if (b + n) > 0 else 1.0
    return beta * q_rave + (1 - beta) * q_uct

def _get_last_n_actions(node: Node, n: int) -> list[str]:
    actions = []
    while node is not None and len(actions) <= n:
        actions.append(node.group)
        node = node.parent
    return list(reversed(actions))  # Reverse to get root → leaf order


def expand_group(node: Node, grouped_nodes: dict = {}):
    leaf_nodes = []
    for group, quantum_circuits in grouped_nodes.items():
        if not quantum_circuits:
            continue

        # Expand Subgroup nodes
        subgroup_node = node_from_qc(node.state.circuit, node, roll_out=False)
        subgroup_node.group = group

        # decrement the tree depth by 1 since this grouping node does not have a circuit
        subgroup_node.tree_depth = subgroup_node.tree_depth - 1

        if node.group == "change":
            subgroup_node.is_finite = False

        # Expand circuits in the Subgroup
        for qc in quantum_circuits:
            new_leaf_node = node_from_qc(qc, subgroup_node, roll_out=False)
            new_leaf_node.group = group
            leaf_nodes.append(new_leaf_node)

    return leaf_nodes


def expand_circuit(
    node: Node,
    group_by_gates: bool,
    group_by_action: bool,
    terminal_nodes: bool,
    group_by_change: bool,
    group_by_swap: bool,
    finite_progressive_widening: bool,
):
    leaf_nodes = []
    nodes_to_expand = []

    gates = ["cx", "rx", "ry", "rz"]

    if group_by_action:
        actions = {
            "add": structure.get_add_options,
            "delete": structure.get_delete_options,
            "swap": structure.get_swap_options,
            "change": None,
        }

        if terminal_nodes:
            actions["stop"] = None

        # Define all to_expand
        for action, instructions in actions.items():
            action_node = node_from_qc(node.state.circuit, node, roll_out=False)
            action_node.group = action
            action_node.tree_depth = action_node.tree_depth - 1

            if action == "stop":
                action_node.isTerminal = True
                leaf_nodes.append(action_node)
                continue

            # create extra gate nodes below the action node
            if (action == "add" and group_by_gates) or (
                action == "swap" and group_by_swap
            ):
                for gate in gates:
                    group_node = node_from_qc(
                        node.state.circuit, action_node, roll_out=False
                    )
                    group_node.group = f"{action}_{gate}"
                    group_node.tree_depth = group_node.tree_depth - 1

                    # Define expansions
                    group_node.to_expand = instructions(node.state.circuit, gate=gate)
                    nodes_to_expand.append(group_node)

            elif action == "change" and group_by_change:
                # Expand leaf nodes
                new_leaf_nodes = expand_group(
                    action_node,
                    grouped_nodes=structure.get_all_parameter_changes(
                        node.state.circuit
                    ),
                )

                if new_leaf_nodes:
                    leaf_nodes += new_leaf_nodes
                else:
                    node.children.remove(action_node)

            # General logic for each action
            elif action == "change":
                action_node.is_finite = False

                new_quantum_circuits = structure.get_parameter_change(
                    action_node.state.circuit,
                )

                if new_quantum_circuits:
                    new_quantum_circuit = new_quantum_circuits[0]
                    new_leaf_node = node_from_qc(
                        new_quantum_circuit, action_node, roll_out=False
                    )
                    new_leaf_node.group = node.group

                    # Expand leaf nodes
                    leaf_nodes.append(new_leaf_node)
                else:
                    node.children.remove(action_node)

            else:
                # Define expansions
                action_node.to_expand = instructions(node.state.circuit)
                nodes_to_expand.append(action_node)


    elif group_by_gates:
        # Add nodes
        for gate in gates:
            group_node = node_from_qc(node.state.circuit, node, roll_out=False)
            group_node.group = f"add_{gate}"
            group_node.tree_depth = group_node.tree_depth - 1

            # Define expansions
            group_node.to_expand = structure.get_add_options(
                node.state.circuit, gate=gate
            )
            nodes_to_expand.append(group_node)

        # Delete node
        group_node = node_from_qc(node.state.circuit, node, roll_out=False)
        group_node.group = "delete"
        group_node.tree_depth = group_node.tree_depth - 1

        # Define expansions
        group_node.to_expand = structure.get_delete_options(node.state.circuit)
        nodes_to_expand.append(group_node)

        # Expand stop node
        if terminal_nodes:
            new_stop_node = node_from_qc(node.state.circuit, node, roll_out=False)
            new_stop_node.isTerminal = True
            new_stop_node.group = "stop"

            # Expand leaf node
            leaf_nodes.append(new_stop_node)

    # Expand the nodes to expand
    for new_node in nodes_to_expand:
        if new_node.to_expand:
            leaf_nodes.append(expand_finite_group(new_node))

            if not finite_progressive_widening:
                # Expand all the nodes in the to_expand list
                while new_node.to_expand:
                    leaf_nodes.append(expand_finite_group(new_node))
        else:
            # Remove the group node if it has no children
            new_node.parent.children.remove(new_node)

            # Remove the supergroup node if it has no children
            if (
                len(new_node.parent.children) == 0
                and len(new_node.parent.to_expand) == 0
            ):
                new_node.parent.parent.children.remove(new_node.parent)

    return leaf_nodes


def expand_infinite_group(node: Node) -> Node:
    """This function expands a infinite group node by adding a new child node"""
    new_quantum_circuits = structure.get_parameter_change(
        node.state.circuit,
        position=int(node.group.split("_")[1]) if "_" in node.group else None,
    )
    if new_quantum_circuits:
        new_quantum_circuit = new_quantum_circuits[0]
        new_leaf_node = node_from_qc(new_quantum_circuit, node, roll_out=False)
        new_leaf_node.group = node.group
        return new_leaf_node


def expand_finite_group(node: Node) -> Node:
    """
    expands a finite node by one child and pops that child from the to_expand list
    :param node: group node with a non-empty to_expand list
    returns: A new child node (Node)
    """
    instructions = node.to_expand.pop(random.randrange(len(node.to_expand)))
    action = node.group.split("_")[0]

    # Make new leaf node
    circuit = structure.perform_action(node.state.circuit, action, instructions)
    new_leaf_node = node_from_qc(circuit, node, roll_out=False)
    new_leaf_node.group = node.group
    return new_leaf_node


def rollout(node: Node, steps: int) -> Node:
    return node


def evaluate(node: Node, evaluation_function) -> float:
    eval = node.state.evaluation(evaluation_function)
    if not isinstance(eval, float):
        eval = eval.item()

    node.evaluation_value = eval
    return eval


def backpropagate(node: Node, result: float, selection_method: str, n: int) -> None:
    visited_nodes = [] # for rave (dont actully need, can move reward and child iteration to while loop)
    amaf_actions = set() # for rave
    action_sequence_reverse = [] # for n-grams

    while node is not None:
        node.visits += 1
        node.value += result
        if selection_method == 'UCB-tuned': node.squared_value += result ** 2  # Track sum of squared rewards for UCB-tuned
        if selection_method == 'RAVE': 
            visited_nodes.append(node) # save visited nodes for RAVE
            amaf_actions.add(node.group)
        if selection_method == 'n-grams': 
            action_sequence_reverse.append(node.group)  # Build the reverse action sequence

            # Only store n-grams once we have enough actions
            if len(action_sequence_reverse) >= n:
                ngram = tuple(reversed(action_sequence_reverse[-n:]))  # Make it forward-facing
                n_gram_stats[ngram].append(result)
                action_sequence_reverse.pop(0)
        node = node.parent

    # Update RAVE values for all visited nodes
    for node in visited_nodes:
        node.n_rave += 1
        node.q_rave += result

        for child in node.children:
            if child.group in amaf_actions:
                child.n_rave += 1
                child.q_rave += result


def modify_prob_choice(dictionary: dict, len_qc: int) -> dict:
    keys = list(dictionary.keys())
    values = list(dictionary.values())
    modifications = [-40, 10, 10, 10, 10]
    modified_values = [max(0, v + m) for v, m in zip(values, modifications)]
    if len_qc < 6:
        modified_values[1] = 0
    # Normalize to ensure the sum is still 100
    modified_values = [v / sum(modified_values) * 100 for v in modified_values]
    return dict(zip(keys, modified_values))


def commit(epsilon: float, current_node: Node, criteria: str) -> Node:
    # It commits to the best action if the node has explored enough
    return current_node.best_child(criteria=criteria)
    # if epsilon is not None:
    #     if random.uniform(0, 1) >= epsilon:
    #         return current_node.best_child(criteria=criteria)
    # return current_node.best_child(criteria=criteria)


def save_data(node: Node, spend: int, epoch: int, parent_value: float) -> list:
    """
    Collects the data to be put in the dataframe

    return: ["budget", "expandedBy", "objectiveValue","epoch", "treeDepth", "parentValue", "H","Rx","Ry","Rz","Cx"]
    """
    if node.isTerminal:
        parent_node = node.parent
        while parent_node.evaluation_value is None:
            parent_node = parent_node.parent
        value = parent_node.evaluation_value
    elif not node.parent:
        value = node.evaluation_value
    else:
        value = node.value / node.visits

    gate_counts = dict(node.state.circuit.count_ops())
    return [
        spend,
        node.group,
        value,
        epoch,
        node.tree_depth,
        parent_value,
        gate_counts["h"] if "h" in gate_counts.keys() else 0,
        gate_counts["rx"] if "rx" in gate_counts.keys() else 0,
        gate_counts["ry"] if "ry" in gate_counts.keys() else 0,
        gate_counts["rz"] if "rz" in gate_counts.keys() else 0,
        gate_counts["cx"] if "cx" in gate_counts.keys() else 0,
    ]


def mcts(
    root: Node,
    budget: int,  # Number of evaluations
    evaluation_function,  # Based on the quantum problem
    max_terminal_visits_percentage: float = 0.02,
    finite_progressive_widening: bool = True,
    # Default parameters
    branches=False,
    criteria: str = "value",
    epsilon: float = None,
    stop_deterministic: bool = False,
    roll_out_steps: int = 0,
    rollout_type: str = "classic",
    ucb_value: float = 0.4,
    pw_C=1,
    pw_alpha=0.3,
    verbose: bool = False,
    # Test dependendt parameters
    group_by_gates: bool = False,
    group_by_action: bool = False,
    terminal_nodes: bool = False,
    group_by_change: bool = False,
    group_by_swap: bool = False,
    collect_data: bool = False,
    selection_method: str = 'UCB',
    n: int = 2 # for n-grams selection method
) -> dict:
    best_node = root
    best_value = float("-inf")

    # a = add gate, d = delete gate, s = swap gates, c = change parameter
    original_root = root
    # dataframe to be filled with the selected node at each epoch
    objective_values = pd.DataFrame(
        columns=[
            "budget",
            "expandedBy",
            "objectiveValue",
            "epoch",
            "treeDepth",
            "parentValue",
            "H",
            "Rx",
            "Ry",
            "Rz",
            "Cx",
        ]
    )
    if verbose:
        print("Root Node:\n", root)

    evaluate(root, evaluation_function)
    root.visits = 1
    root.value = root.evaluation_value
    epoch_counter = 0

    max_terminal_visits = max_terminal_visits_percentage * budget
    spend = 0

    objective_values.loc[len(objective_values)] = save_data(
        root, spend, epoch_counter, 0
    )
    while spend < budget:
        epoch_counter += 1
        current_node = root

        # budget/20 means we permanently commit to best option once a node has used 5% of the total search budget.
        # if current_node.visits > budget / 20 and len(current_node.children) > 2:
        #     root = commit(epsilon, current_node, criteria)
        #     if verbose:
        #         print("Committed to", root)
        #     current_node = root

        if verbose:
            print("Epoch Counter: ", epoch_counter)

        # Selection
        while not current_node.isTerminal and current_node.is_fully_expanded(
            branches=branches,
            pw_C=pw_C,
            pw_alpha=pw_alpha,
            finite_progressive_widening=finite_progressive_widening,
        ):
            current_node = select(current_node, ucb_value, max_terminal_visits, method=selection_method, n=n)

            if verbose:
                print("Selection: ", current_node)

        initial_parent_value = current_node.value / current_node.visits

        # Expansion
        new_nodes = []
        if not current_node.isTerminal:
            if not current_node.is_finite:
                # If the current node is a group node witch is infinite expandable
                new_nodes.append(expand_infinite_group(current_node))
            elif current_node.to_expand and finite_progressive_widening:
                new_nodes.append(expand_finite_group(current_node))
            else:
                # Leaf node expansion
                new_nodes = expand_circuit(
                    current_node,
                    group_by_gates=group_by_gates,
                    group_by_action=group_by_action,
                    terminal_nodes=terminal_nodes,
                    group_by_change=group_by_change,
                    group_by_swap=group_by_swap,
                    finite_progressive_widening=finite_progressive_widening,
                )

        if not new_nodes and current_node.isTerminal:
            if collect_data:
                objective_values.loc[len(objective_values)] = save_data(
                    current_node, spend, epoch_counter, initial_parent_value
                )
            backpropagate(current_node, current_node.value / current_node.visits, selection_method, n)

        for new_node in new_nodes:
            if verbose:
                print("Node Expanded:\n", new_node)
            if not new_node:
                print(new_nodes)
            # Simulation
            if not new_node.isTerminal:
                if isinstance(roll_out_steps, int):
                    leaf_node = rollout(new_node, steps=roll_out_steps)
                    result = evaluate(leaf_node, evaluation_function)
                    spend += 1

                    if roll_out_steps > 1 and rollout_type != "classic":
                        node_to_evaluate = leaf_node
                        result_list = [result]
                        for _ in range(roll_out_steps):
                            result_list.append(
                                evaluate(node_to_evaluate.parent, evaluation_function)
                            )
                            node_to_evaluate = node_to_evaluate.parent
                        if rollout_type == "max":
                            result = max(result_list)
                        elif rollout_type == "mean":
                            result = sum(result_list) / len(result_list)
                        else:
                            raise NotImplementedError(
                                f"Rollout type '{rollout_type}' is not implemented."
                            )
                else:
                    raise TypeError("The variable roll_out_steps must be an integer")
            elif new_node.value == 0:
                result = evaluate(new_node, evaluation_function)
                spend += 1
            else:
                parent_node = new_node.parent
                while parent_node.evaluation_value is None:
                    parent_node = parent_node.parent
                result = parent_node.evaluation_value

            # update best value
            if result > best_value:
                best_value = result
                best_node = new_node

            if verbose:
                print("Reward: ", result)

            # Backpropagation
            backpropagate(new_node, result, selection_method, n)

            # Store data
            if result and collect_data:
                objective_values.loc[len(objective_values)] = save_data(
                    new_node, spend, epoch_counter, initial_parent_value
                )

    # Return the best
    best_greedy_node = original_root
    # path = []
    qc_path = []
    children, value, visits = [], [], []
    while not best_greedy_node.isTerminal and len(best_greedy_node.children) >= 1:
        # path.append(best_greedy_node)
        qc_path.append(best_greedy_node.state.circuit)
        children.append(len(best_greedy_node.children))
        value.append(best_greedy_node.value)
        visits.append(best_greedy_node.visits)
        best_greedy_node = best_greedy_node.best_child(criteria=criteria)

    return {
        "qc": qc_path,
        "children": children,
        "visits": visits,
        "value": value,
        "data": objective_values,
        "best_qc": best_node.state.circuit,
    }
